# Generated by Django 5.0.6 on 2024-06-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('brand', models.CharField(max_length=80, verbose_name='Brand')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
    ]
